// Generated by CoffeeScript 1.3.3
(function() {
  var LanguageOptionViewModel, ListSortingOptionViewModel, PrioritiesViewModel;

  LanguageOptionViewModel = function(locale) {
    this.id = locale;
    this.label = kb.locale_manager.localeToLabel(locale);
    this.option_group = 'lang';
    return this;
  };

  PrioritiesViewModel = function(model) {
    this.priority = model.get('id');
    this.priority_text = kb.observable(kb.locale_manager, {
      key: this.priority
    });
    this.priority_color = kb.observable(model, {
      key: 'color'
    });
    return this;
  };

  ListSortingOptionViewModel = function(string_id) {
    this.id = string_id;
    this.label = kb.observable(kb.locale_manager, {
      key: string_id
    });
    this.option_group = 'list_sort';
    return this;
  };

  window.AppSettingsViewModel = function() {
    var priorities,
      _this = this;
    window.app_settings = this;
    this.collections = {
      priorities: new PriorityCollection()
    };
    _.delay((function() {
      _this.collections.priorities.fetch({
        success: function(collection) {
          if (!collection.get('high')) {
            collection.create({
              id: 'high',
              color: '#bf30ff'
            });
          }
          if (!collection.get('medium')) {
            collection.create({
              id: 'medium',
              color: '#98acff'
            });
          }
          if (!collection.get('low')) {
            return collection.create({
              id: 'low',
              color: '#38ff6a'
            });
          }
        }
      });
      $('.colorpicker').mColorPicker({
        imageFolder: $.fn.mColorPicker.init.imageFolder
      });
      return $('.colorpicker').bind('colorpicked', function() {
        var model;
        model = _this.collections.priorities.get($(_this).attr('id'));
        if (model) {
          return model.save({
            color: $(_this).val()
          });
        }
      });
    }), 1000);
    this.language_options = _.map(kb.locale_manager.getLocales(), function(locale) {
      return new LanguageOptionViewModel(locale);
    });
    this.current_language = ko.observable();
    this.selected_language = ko.computed({
      read: function() {
        return _this.current_language();
      },
      write: function(new_locale) {
        kb.locale_manager.setLocale(new_locale);
        return _this.current_language(new_locale);
      }
    });
    this.selected_language('en');
    priorities = [new Backbone.ModelRef(this.collections.priorities, 'high'), new Backbone.ModelRef(this.collections.priorities, 'medium'), new Backbone.ModelRef(this.collections.priorities, 'low')];
    this.priorities = _.map(priorities, function(model) {
      return new PrioritiesViewModel(model);
    });
    this.getColorByPriority = function(priority) {
      var view_model, _i, _len, _ref;
      this.createColorsDependency();
      _ref = this.priorities;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        view_model = _ref[_i];
        if (view_model.priority === priority) {
          return view_model.priority_color();
        }
      }
      return '';
    };
    this.createColorsDependency = function() {
      var view_model, _i, _len, _ref;
      _ref = _this.priorities;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        view_model = _ref[_i];
        view_model.priority_color();
      }
    };
    this.default_priority = ko.observable('medium');
    this.default_priority_color = ko.computed(function() {
      return _this.getColorByPriority(_this.default_priority());
    });
    this.priorityToRank = function(priority) {
      switch (priority) {
        case 'high':
          return 0;
        case 'medium':
          return 1;
        case 'low':
          return 2;
      }
    };
    this.list_sorting_options = [new ListSortingOptionViewModel('label_title'), new ListSortingOptionViewModel('label_created'), new ListSortingOptionViewModel('label_priority')];
    this.selected_list_sorting = ko.observable('label_title');
    return this;
  };

}).call(this);
