// Generated by CoffeeScript 1.3.3
(function() {

  window.FooterViewModel = function(todos) {
    var _this = this;
    this.todos = kb.collectionObservable(todos, {
      models_only: true
    });
    this.onDestroyCompleted = function() {
      return todos.destroyCompleted();
    };
    return this;
  };

}).call(this);
