// Generated by CoffeeScript 1.3.1
(function() {
  var TodoViewModel;

  TodoViewModel = function(model) {
    var tooltip_visible,
      _this = this;
    this.editing = ko.observable(false);
    this.completed = kb.observable(model, {
      key: 'completed',
      read: (function() {
        return model.completed();
      }),
      write: (function(completed) {
        return model.completed(completed);
      })
    }, this);
    this.visible = ko.computed(function() {
      switch (app.viewmodels.settings.list_filter_mode()) {
        case 'active':
          return !_this.completed();
        case 'completed':
          return _this.completed();
        default:
          return true;
      }
    });
    this.title = kb.observable(model, {
      key: 'title',
      write: (function(title) {
        if ($.trim(title)) {
          model.save({
            title: $.trim(title)
          });
        } else {
          _.defer(function() {
            return model.destroy();
          });
        }
        return _this.editing(false);
      })
    }, this);
    this.onDestroyTodo = function() {
      return model.destroy();
    };
    this.onCheckEditBegin = function() {
      if (!_this.editing() && !_this.completed()) {
        _this.editing(true);
        return $('.todo-input').focus();
      }
    };
    this.onCheckEditEnd = function(view_model, event) {
      if ((event.keyCode === 13) || (event.type === 'blur')) {
        $('.todo-input').blur();
        return _this.editing(false);
      }
    };
    this.created_at = model.get('created_at');
    this.completed_at = kb.observable(model, {
      key: 'completed',
      localizer: LongDateLocalizer
    });
    this.completed_text = ko.computed(function() {
      var completed_at;
      completed_at = _this.completed_at();
      if (!!completed_at) {
        return "" + (kb.locale_manager.get('label_completed')) + ": " + completed_at;
      } else {
        return '';
      }
    });
    this.priority_color = kb.observable(model, {
      key: 'priority',
      read: function() {
        return app.viewmodels.settings.getColorByPriority(model.get('priority'));
      }
    });
    this.tooltip_visible = ko.observable(false);
    tooltip_visible = this.tooltip_visible;
    this.onSelectPriority = function(view_model, event) {
      event.stopPropagation();
      tooltip_visible(false);
      return model.save({
        priority: ko.utils.unwrapObservable(this.priority)
      });
    };
    this.onToggleTooltip = function() {
      return _this.tooltip_visible(!_this.tooltip_visible());
    };
    return this;
  };

  window.TodosViewModel = function(todos) {
    var _this = this;
    this.todos = kb.collectionObservable(todos, {
      view_model: TodoViewModel,
      sort_attribute: 'title'
    });
    this.todos.collection().bind('change', function() {
      return _this.todos.valueHasMutated();
    });
    this.sort_mode = ko.computed(function() {
      var new_mode;
      new_mode = app.viewmodels.settings.selected_list_sorting();
      return _.defer(function() {
        switch (new_mode) {
          case 'label_title':
            return _this.todos.sortAttribute('title');
          case 'label_created':
            return _this.todos.sortedIndex(function(models, model) {
              return _.sortedIndex(models, model, function(test) {
                return kb.utils.wrappedModel(test).get('created_at').valueOf();
              });
            });
          case 'label_priority':
            return _this.todos.sortedIndex(function(models, model) {
              var _this = this;
              return _.sortedIndex(models, model, function(test) {
                return app.viewmodels.settings.priorityToRank(kb.utils.wrappedModel(test).get('priority'));
              });
            });
        }
      });
    });
    this.tasks_exist = ko.computed(function() {
      return _this.todos().length;
    });
    this.all_completed = ko.computed({
      read: function() {
        return !_this.todos.collection().remainingCount();
      },
      write: function(completed) {
        return _this.todos.collection().completeAll(completed);
      }
    });
    this.completed_all_text = kb.observable(kb.locale_manager, {
      key: 'completed_all'
    });
    return this;
  };

}).call(this);
